cmake_minimum_required(VERSION 4.3)
project(Parcial1)

set(CMAKE_CXX_STANDARD 20)

add_executable(Parcial1 main.cpp)
add_executable(TipoDato TipoDato.cpp)
add_executable(VariablesConstantes VariablesConstantes.cpp)
add_executable(Megamente Megamente.cpp)
add_executable(EntradaSalidaDatos EntradaSalidaDatos.cpp)
add_executable(IfSimple IfSimple.cpp)
add_executable(ifElse ifElse.cpp)
